#!/bin/sh

# Get Application Install Directory
if (cat /etc/palm/luna.conf | grep -i "/media/cryptofs/apps") ; then
	INSTDIR=/media/cryptofs/apps
else
	INSTDIR=/var
fi

rootfs_open -w
rm -rf /usr/palm/frameworks/mojo/justinput/
rm -f /usr/lib/luna/java/justinput.jar
rm -f /usr/share/dbus-1/system-services/com.youjf.jisrv.service
rm -f /etc/event.d/com.youjf.com.justinput
mv -f /usr/palm/frameworks/mojo/builtins/palmInitFramework338.js.jeffery /usr/palm/frameworks/mojo/builtins/palmInitFramework338.js

HackFile="/usr/palm/frameworks/mojo/mojo.js"
StartLine=`sed -n "/justinput hack start/=" ${HackFile}`
EndLine=`sed -n "/justinput hack end/=" ${HackFile}`
if ((test ${StartLine} > 0) && (test ${EndLine} > 0)) then
    cp -f ${HackFile} ${HackFile}.old
    sed "${StartLine},${EndLine}d" "${HackFile}" > ${HackFile}.tmp
    mv -f ${HackFile}.tmp ${HackFile}
fi

exit 0
