#!/bin/sh
mount -o remount,rw /
INSTDIR=/media/cryptofs/apps
PATCHDIR=$INSTDIR/usr/palm/applications/com.youjf.webpatch/
# a fully hack of framework
if [ -f "/usr/palm/frameworks/mojo/builtins/palmInitFramework338.js" ]; then
    mv -f $PATCHDIR/palmInitFramework338.js /usr/palm/frameworks/mojo/builtins/
fi

if [ -f "/usr/palm/frameworks/mojo/builtins/palmInitFramework347.js" ]; then
    mv -f $PATCHDIR/palmInitFramework347.js /usr/palm/frameworks/mojo/builtins/
fi

exit 0
