#!/bin/sh

# Get Application Install Directory
if (cat /etc/palm/luna.conf | grep -i "/media/cryptofs/apps") ; then
	INSTDIR=/media/cryptofs/apps
else
	INSTDIR=/var
fi

# install service
mv -f $INSTDIR/usr/palm/applications/com.youjf.justinput/justinput/ /usr/palm/frameworks/mojo/
mv -f $INSTDIR/usr/palm/applications/com.youjf.justinput/service/justinput.jar /usr/lib/luna/java/
chmod +x /usr/lib/luna/java/justinput.jar
mv -f $INSTDIR/usr/palm/applications/com.youjf.justinput/service/com.youjf.jisrv.service /usr/share/dbus-1/system-services/
chmod +x /usr/share/dbus-1/system-services/com.youjf.jisrv.service
mv -f $INSTDIR/usr/palm/applications/com.youjf.justinput/service/com.youjf.com.justinput /etc/event.d/

HackFile="/usr/palm/frameworks/mojo/mojo.js"
StartLine=`sed -n "/justinput hack start/=" ${HackFile}`
EndLine=`sed -n "/justinput hack end/=" ${HackFile}`
if ((test ${StartLine} > 0) && (test ${EndLine} > 0)) then
    cp -f ${HackFile} ${HackFile}.old
    sed "${StartLine},${EndLine}d" "${HackFile}" > ${HackFile}.tmp
    mv -f ${HackFile}.tmp ${HackFile}
fi

# hack the mojo.js
cat $INSTDIR/usr/palm/applications/com.youjf.justinput/service/mojo_append.key.js >> ${HackFile}

rm -rf $INSTDIR/usr/palm/applications/com.youjf.justinput/service/

luna-send -n 1 luna://com.youjf.jisrv/status '{}' >/dev/null 2>&1

exit 0
