#!/bin/sh
mount -o remount,rw /
# Get Application Install Directory
if (cat /etc/palm/luna.conf | grep -i "/media/cryptofs/apps") ; then
	INSTDIR=/media/cryptofs/apps
else
	INSTDIR=/var
fi

DBPATH=/home/root/.justinput/db/
mkdir -p $DBPATH

mv -f $INSTDIR/usr/palm/applications/com.youjf.justinput/justinput/db/wb.db $DBPATH
mv -f $INSTDIR/usr/palm/applications/com.youjf.justinput/justinput/db/config.db $DBPATH

rm -rf $INSTDIR/usr/palm/applications/com.youjf.justinput/justinput/

exit 0
